// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv';
import { defineConfig, env } from 'prisma/config';

// NODE_ENV must come from the shell / Docker / compose environment.
// It is not read from .env yet when this file is evaluated.
config({ path: '.env.development' });

if (process.env.NODE_ENV === 'production') {
    config({ path: '.env', override: true });
}

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations/dev',
    },
    datasource: {
        url: env('DATABASE_URL'),
    },
});
