// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv';
import { defineConfig, env } from 'prisma/config';

config({
    path: process.env.NODE_ENV === 'production' ? '.env.production' : '.env.development',
});

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations/dev',
    },
    datasource: {
        url: env('DATABASE_URL'),
    },
});
